// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=../mocks/auth.mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	request "user_service/dto/request"
	response "user_service/dto/response"

	gomock "go.uber.org/mock/gomock"
)

// MockIRegistration is a mock of IRegistration interface.
type MockIRegistration struct {
	ctrl     *gomock.Controller
	recorder *MockIRegistrationMockRecorder
	isgomock struct{}
}

// MockIRegistrationMockRecorder is the mock recorder for MockIRegistration.
type MockIRegistrationMockRecorder struct {
	mock *MockIRegistration
}

// NewMockIRegistration creates a new mock instance.
func NewMockIRegistration(ctrl *gomock.Controller) *MockIRegistration {
	mock := &MockIRegistration{ctrl: ctrl}
	mock.recorder = &MockIRegistrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRegistration) EXPECT() *MockIRegistrationMockRecorder {
	return m.recorder
}

// CompleteRegistration mocks base method.
func (m *MockIRegistration) CompleteRegistration(ctx context.Context, arg request.CompleteRegistrationReq) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteRegistration", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteRegistration indicates an expected call of CompleteRegistration.
func (mr *MockIRegistrationMockRecorder) CompleteRegistration(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteRegistration", reflect.TypeOf((*MockIRegistration)(nil).CompleteRegistration), ctx, arg)
}

// SendRegistrationOtp mocks base method.
func (m *MockIRegistration) SendRegistrationOtp(ctx context.Context, arg request.SendOtpReq) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRegistrationOtp", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendRegistrationOtp indicates an expected call of SendRegistrationOtp.
func (mr *MockIRegistrationMockRecorder) SendRegistrationOtp(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRegistrationOtp", reflect.TypeOf((*MockIRegistration)(nil).SendRegistrationOtp), ctx, arg)
}

// VerifyRegistrationOtp mocks base method.
func (m *MockIRegistration) VerifyRegistrationOtp(ctx context.Context, arg request.VerifyOtpReq) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRegistrationOtp", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRegistrationOtp indicates an expected call of VerifyRegistrationOtp.
func (mr *MockIRegistrationMockRecorder) VerifyRegistrationOtp(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRegistrationOtp", reflect.TypeOf((*MockIRegistration)(nil).VerifyRegistrationOtp), ctx, arg)
}

// MockILogin is a mock of ILogin interface.
type MockILogin struct {
	ctrl     *gomock.Controller
	recorder *MockILoginMockRecorder
	isgomock struct{}
}

// MockILoginMockRecorder is the mock recorder for MockILogin.
type MockILoginMockRecorder struct {
	mock *MockILogin
}

// NewMockILogin creates a new mock instance.
func NewMockILogin(ctrl *gomock.Controller) *MockILogin {
	mock := &MockILogin{ctrl: ctrl}
	mock.recorder = &MockILoginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogin) EXPECT() *MockILoginMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockILogin) Login(ctx context.Context, arg request.LoginReq) (response.LoginRes, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, arg)
	ret0, _ := ret[0].(response.LoginRes)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockILoginMockRecorder) Login(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockILogin)(nil).Login), ctx, arg)
}

// MockIForgotPassword is a mock of IForgotPassword interface.
type MockIForgotPassword struct {
	ctrl     *gomock.Controller
	recorder *MockIForgotPasswordMockRecorder
	isgomock struct{}
}

// MockIForgotPasswordMockRecorder is the mock recorder for MockIForgotPassword.
type MockIForgotPasswordMockRecorder struct {
	mock *MockIForgotPassword
}

// NewMockIForgotPassword creates a new mock instance.
func NewMockIForgotPassword(ctrl *gomock.Controller) *MockIForgotPassword {
	mock := &MockIForgotPassword{ctrl: ctrl}
	mock.recorder = &MockIForgotPasswordMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIForgotPassword) EXPECT() *MockIForgotPasswordMockRecorder {
	return m.recorder
}

// CompleteForgotPassword mocks base method.
func (m *MockIForgotPassword) CompleteForgotPassword(ctx context.Context, arg request.CompleteForgotPasswordReq) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteForgotPassword", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteForgotPassword indicates an expected call of CompleteForgotPassword.
func (mr *MockIForgotPasswordMockRecorder) CompleteForgotPassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteForgotPassword", reflect.TypeOf((*MockIForgotPassword)(nil).CompleteForgotPassword), ctx, arg)
}

// SendForgotPasswordOtp mocks base method.
func (m *MockIForgotPassword) SendForgotPasswordOtp(ctx context.Context, arg request.SendOtpReq) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendForgotPasswordOtp", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendForgotPasswordOtp indicates an expected call of SendForgotPasswordOtp.
func (mr *MockIForgotPasswordMockRecorder) SendForgotPasswordOtp(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendForgotPasswordOtp", reflect.TypeOf((*MockIForgotPassword)(nil).SendForgotPasswordOtp), ctx, arg)
}

// VerifyForgotPasswordOtp mocks base method.
func (m *MockIForgotPassword) VerifyForgotPasswordOtp(ctx context.Context, arg request.VerifyOtpReq) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyForgotPasswordOtp", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyForgotPasswordOtp indicates an expected call of VerifyForgotPasswordOtp.
func (mr *MockIForgotPasswordMockRecorder) VerifyForgotPasswordOtp(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyForgotPasswordOtp", reflect.TypeOf((*MockIForgotPassword)(nil).VerifyForgotPasswordOtp), ctx, arg)
}

// MockILogout is a mock of ILogout interface.
type MockILogout struct {
	ctrl     *gomock.Controller
	recorder *MockILogoutMockRecorder
	isgomock struct{}
}

// MockILogoutMockRecorder is the mock recorder for MockILogout.
type MockILogoutMockRecorder struct {
	mock *MockILogout
}

// NewMockILogout creates a new mock instance.
func NewMockILogout(ctrl *gomock.Controller) *MockILogout {
	mock := &MockILogout{ctrl: ctrl}
	mock.recorder = &MockILogoutMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogout) EXPECT() *MockILogoutMockRecorder {
	return m.recorder
}

// Logout mocks base method.
func (m *MockILogout) Logout(ctx context.Context, email string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, email)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockILogoutMockRecorder) Logout(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockILogout)(nil).Logout), ctx, email)
}

// MockIOAuth2 is a mock of IOAuth2 interface.
type MockIOAuth2 struct {
	ctrl     *gomock.Controller
	recorder *MockIOAuth2MockRecorder
	isgomock struct{}
}

// MockIOAuth2MockRecorder is the mock recorder for MockIOAuth2.
type MockIOAuth2MockRecorder struct {
	mock *MockIOAuth2
}

// NewMockIOAuth2 creates a new mock instance.
func NewMockIOAuth2(ctrl *gomock.Controller) *MockIOAuth2 {
	mock := &MockIOAuth2{ctrl: ctrl}
	mock.recorder = &MockIOAuth2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOAuth2) EXPECT() *MockIOAuth2MockRecorder {
	return m.recorder
}

// CheckOAuth2UserByEmail mocks base method.
func (m *MockIOAuth2) CheckOAuth2UserByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOAuth2UserByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckOAuth2UserByEmail indicates an expected call of CheckOAuth2UserByEmail.
func (mr *MockIOAuth2MockRecorder) CheckOAuth2UserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOAuth2UserByEmail", reflect.TypeOf((*MockIOAuth2)(nil).CheckOAuth2UserByEmail), ctx, email)
}

// InserOAuth2UsertUser mocks base method.
func (m *MockIOAuth2) InserOAuth2UsertUser(ctx context.Context, arg response.OAuth2UserInfo) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InserOAuth2UsertUser", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InserOAuth2UsertUser indicates an expected call of InserOAuth2UsertUser.
func (mr *MockIOAuth2MockRecorder) InserOAuth2UsertUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InserOAuth2UsertUser", reflect.TypeOf((*MockIOAuth2)(nil).InserOAuth2UsertUser), ctx, arg)
}

// ReturnToken mocks base method.
func (m *MockIOAuth2) ReturnToken(ctx context.Context, email string) (response.LoginRes, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnToken", ctx, email)
	ret0, _ := ret[0].(response.LoginRes)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReturnToken indicates an expected call of ReturnToken.
func (mr *MockIOAuth2MockRecorder) ReturnToken(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnToken", reflect.TypeOf((*MockIOAuth2)(nil).ReturnToken), ctx, email)
}
