// Code generated by MockGen. DO NOT EDIT.
// Source: message_broker.go
//
// Generated by this command:
//
//	mockgen -source=message_broker.go -destination=../internal/mocks/message_broker_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIMessageBroker is a mock of IMessageBroker interface.
type MockIMessageBroker struct {
	ctrl     *gomock.Controller
	recorder *MockIMessageBrokerMockRecorder
	isgomock struct{}
}

// MockIMessageBrokerMockRecorder is the mock recorder for MockIMessageBroker.
type MockIMessageBrokerMockRecorder struct {
	mock *MockIMessageBroker
}

// NewMockIMessageBroker creates a new mock instance.
func NewMockIMessageBroker(ctrl *gomock.Controller) *MockIMessageBroker {
	mock := &MockIMessageBroker{ctrl: ctrl}
	mock.recorder = &MockIMessageBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMessageBroker) EXPECT() *MockIMessageBrokerMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockIMessageBroker) SendMessage(topic, key string, message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", topic, key, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockIMessageBrokerMockRecorder) SendMessage(topic, key, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockIMessageBroker)(nil).SendMessage), topic, key, message)
}
