// Code generated by MockGen. DO NOT EDIT.
// Source: message_broker.go
//
// Generated by this command:
//
//	mockgen -source=message_broker.go -destination=../mocks/message_broker.mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIMessageBrokerWriter is a mock of IMessageBrokerWriter interface.
type MockIMessageBrokerWriter struct {
	ctrl     *gomock.Controller
	recorder *MockIMessageBrokerWriterMockRecorder
	isgomock struct{}
}

// MockIMessageBrokerWriterMockRecorder is the mock recorder for MockIMessageBrokerWriter.
type MockIMessageBrokerWriterMockRecorder struct {
	mock *MockIMessageBrokerWriter
}

// NewMockIMessageBrokerWriter creates a new mock instance.
func NewMockIMessageBrokerWriter(ctrl *gomock.Controller) *MockIMessageBrokerWriter {
	mock := &MockIMessageBrokerWriter{ctrl: ctrl}
	mock.recorder = &MockIMessageBrokerWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMessageBrokerWriter) EXPECT() *MockIMessageBrokerWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIMessageBrokerWriter) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockIMessageBrokerWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIMessageBrokerWriter)(nil).Close))
}

// SendMessage mocks base method.
func (m *MockIMessageBrokerWriter) SendMessage(ctx context.Context, topic, key string, message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, topic, key, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockIMessageBrokerWriterMockRecorder) SendMessage(ctx, topic, key, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockIMessageBrokerWriter)(nil).SendMessage), ctx, topic, key, message)
}
