DROP TABLE IF EXISTS "user_actions";

DROP TABLE IF EXISTS "user_infos";

ALTER TABLE IF EXISTS "accounts" DROP COLUMN "roles";

DROP TYPE IF EXISTS "roles";

DROP TYPE IF EXISTS "sex";

DROP TABLE IF EXISTS "account";
