version: '3.8'

services:
  bmt_user_service:
    build:
      context: .
    container_name: bmt_user_service
    ports:
      - "5002:5002"
    env_file:
      - app.env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anhiuemlove33
      POSTGRES_DB: bmt_user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  postgres_data: