// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: customer.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInforByEmail = `-- name: GetInforByEmail :one
SELECT email, name, sex, birth_day 
FROM user_infos
WHERE email = $1
`

func (q *Queries) GetInforByEmail(ctx context.Context, email pgtype.Text) (UserInfos, error) {
	row := q.db.QueryRow(ctx, getInforByEmail, email)
	var i UserInfos
	err := row.Scan(
		&i.Email,
		&i.Name,
		&i.Sex,
		&i.BirthDay,
	)
	return i, err
}

const updateInforByEmail = `-- name: UpdateInforByEmail :exec
UPDATE user_infos
SET 
    name = $2, 
    sex = $3,
    birth_day = $4
WHERE email = $1
`

type UpdateInforByEmailParams struct {
	Email    pgtype.Text `json:"email"`
	Name     string      `json:"name"`
	Sex      NullSex     `json:"sex"`
	BirthDay string      `json:"birth_day"`
}

func (q *Queries) UpdateInforByEmail(ctx context.Context, arg UpdateInforByEmailParams) error {
	_, err := q.db.Exec(ctx, updateInforByEmail,
		arg.Email,
		arg.Name,
		arg.Sex,
		arg.BirthDay,
	)
	return err
}
