// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckAccountExistsByEmailAndSource(ctx context.Context, arg CheckAccountExistsByEmailAndSourceParams) (bool, error)
	GetInforByEmail(ctx context.Context, email pgtype.Text) (UserInfos, error)
	GetUserByEmail(ctx context.Context, email string) (Accounts, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) error
	InsertOAuth2Action(ctx context.Context, email pgtype.Text) error
	InsertUserAction(ctx context.Context, email pgtype.Text) error
	InsertUserInfo(ctx context.Context, arg InsertUserInfoParams) error
	UpdateInforByEmail(ctx context.Context, arg UpdateInforByEmailParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUserAction(ctx context.Context, arg UpdateUserActionParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
