// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckAccountExistsByEmail(ctx context.Context, email string) (bool, error)
	GetUserByEmail(ctx context.Context, email string) (Accounts, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) error
	InsertUserAction(ctx context.Context, email pgtype.Text) error
	InsertUserInfo(ctx context.Context, arg InsertUserInfoParams) error
	UpdateAction(ctx context.Context, arg UpdateActionParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
