// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"user_service/db/sqlc"
	"user_service/internal/controllers"
	"user_service/internal/implementations"
	"user_service/internal/injectors/provider"
	"user_service/utils/token/jwt"
)

// Injectors from auth.wire.go:

func InitAuthController() (*controllers.AuthController, error) {
	pool := provider.ProvidePgxPool()
	sqlStore := sqlc.NewStore(pool)
	string2 := provider.ProvideSecretKey()
	iMaker, err := jwt.NewJWTMaker(string2)
	if err != nil {
		return nil, err
	}
	iAuth := implementations.NewAuthService(sqlStore, iMaker)
	authController := controllers.NewAuthController(iAuth)
	return authController, nil
}
